title: Lexiecat!
description: This is going to be the home of my webpage and blog
plugins:
   - jekyll-relative-links
relative_links:
   enabled: true
   collections: true
include:
   - CONTRIBUTING.md
   - README.md
   - LICENSE.md
   - COPYING.md
   - CODE_OF_CONDUCT.md
   - CONTRIBUTING.md
   - ISSUE_TEMPLATE.md
   - PULL_REQUEST_TEMPLATE.md

theme: jekyll-theme-cayman
